# Generated by Django 3.2.5 on 2021-11-29 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='地点名称')),
                ('address', models.CharField(default='', max_length=200, verbose_name='地址')),
                ('latitude', models.FloatField(default=0, verbose_name='纬度')),
                ('longitude', models.FloatField(default=0, verbose_name='经度')),
                ('description', models.TextField(blank=True, null=True, verbose_name='地点描述')),
                ('status', models.IntegerField(choices=[(0, '未发布'), (1, '待审核'), (2, '已发布'), (3, '审核失败')], default=0, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('contributor', models.ManyToManyField(related_name='place_contributor', to=settings.AUTH_USER_MODEL, verbose_name='贡献者')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_create_user', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('photo', models.ManyToManyField(blank=True, related_name='place_related', to='photos.Photo', verbose_name='相关图片')),
            ],
            options={
                'verbose_name': '地点信息',
                'verbose_name_plural': '地点信息',
                'db_table': 'tb_places',
            },
        ),
    ]
