# Generated by Django 3.2.5 on 2021-12-05 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='city',
            field=models.CharField(default='', max_length=100, verbose_name='城市'),
        ),
    ]
