# Generated by Django 3.2.5 on 2021-11-29 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0003_auto_20211129_2148'),
        ('places', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='collection',
        ),
        migrations.AddField(
            model_name='user',
            name='collection_anime',
            field=models.ManyToManyField(blank=True, related_name='collection_user', to='animes.Anime', verbose_name='Anime收藏'),
        ),
        migrations.AddField(
            model_name='user',
            name='collection_place',
            field=models.ManyToManyField(blank=True, related_name='collection_user', to='places.Place', verbose_name='Place收藏'),
        ),
    ]
