# Generated by Django 3.2.5 on 2021-12-05 02:33

from django.db import migrations, models
import nano_backend.utils.fastdfs.fdfs_storage


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='group1/M00/00/00/wKjvgGGoiV-AETMXAAAMK5bwTxs200.jpg', storage=nano_backend.utils.fastdfs.fdfs_storage.FastDFSAvatarStorage, upload_to='avatar', verbose_name='头像'),
        ),
    ]
