# Generated by Django 3.2.5 on 2021-12-18 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0004_auto_20211212_2101'),
        ('users', '0002_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='nickname', max_length=20, verbose_name='昵称'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UserAnimeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animes.anime', verbose_name='Anime')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户Anime历史',
                'verbose_name_plural': '用户Anime历史',
                'db_table': 'tb_user_anime_history',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='history_anime',
            field=models.ManyToManyField(blank=True, related_name='history_user', through='users.UserAnimeHistory', to='animes.Anime', verbose_name='Anime历史'),
        ),
    ]
