# Generated by Django 3.2.5 on 2021-11-29 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211129_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mobile',
            field=models.CharField(default=13012341234, max_length=11, unique=True, verbose_name='手机号'),
            preserve_default=False,
        ),
    ]
