# Generated by Django 3.2.5 on 2021-12-24 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animes', '0001_initial'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('image', models.ImageField(upload_to='recommendation/%Y/%m', verbose_name='图片')),
                ('description', models.CharField(max_length=200, verbose_name='描述')),
                ('score', models.IntegerField(default=0, verbose_name='评分')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animes.anime', verbose_name='动画')),
                ('tags', models.ManyToManyField(to='tags.Tag', verbose_name='标签')),
            ],
            options={
                'verbose_name': '首页推荐',
                'verbose_name_plural': '首页推荐',
                'db_table': 'tb_recommendation',
            },
        ),
    ]
