# Generated by Django 3.2.5 on 2021-12-24 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='type',
            field=models.IntegerField(choices=[(0, '默认'), (1, '轮播图'), (2, '表格')], default=0, verbose_name='推荐条目类型'),
        ),
    ]
