# Generated by Django 3.2.5 on 2021-11-29 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='照片名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='照片描述')),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('type', models.IntegerField(choices=[(0, '实景'), (1, '番剧'), (2, '其他')], default=0, verbose_name='照片类型')),
                ('status', models.IntegerField(choices=[(0, '未发布'), (1, '待审核'), (2, '已发布'), (3, '审核失败')], default=0, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_create_user', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '地点信息',
                'verbose_name_plural': '地点信息',
                'db_table': 'tb_photo',
            },
        ),
    ]
