# Generated by Django 3.2.5 on 2021-12-02 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0007_auto_20211202_1921'),
        ('places', '0002_auto_20211202_1921'),
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='status',
        ),
        migrations.AddField(
            model_name='photo',
            name='anime_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='animes.anime', verbose_name='动画'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='是否通过审核'),
        ),
        migrations.AddField(
            model_name='photo',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='是否公开'),
        ),
        migrations.AddField(
            model_name='photo',
            name='place_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='places.place', verbose_name='地点'),
            preserve_default=False,
        ),
    ]
