# Generated by Django 3.2.5 on 2021-12-05 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name': '照片信息', 'verbose_name_plural': '照片信息'},
        ),
    ]
