# Generated by Django 3.2.5 on 2021-11-28 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='评论内容')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否已删除')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animes.anime', verbose_name='评论对象')),
            ],
        ),
    ]
