# Generated by Django 3.2.5 on 2021-12-24 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staffs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='标题')),
                ('title_cn', models.CharField(blank=True, max_length=100, verbose_name='中文标题')),
                ('description', models.TextField(blank=True, null=True, verbose_name='简介')),
                ('cover', models.ImageField(upload_to='animes/cover', verbose_name='封面图片')),
                ('cover_medium', models.ImageField(upload_to='animes/cover_medium', verbose_name='中等尺寸封面图片')),
                ('cover_small', models.ImageField(upload_to='animes/cover_small', verbose_name='封面图片(正)')),
                ('epi_num', models.IntegerField(default=1, verbose_name='集数')),
                ('website', models.CharField(blank=True, max_length=200, null=True, verbose_name='官网')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='制片国家')),
                ('air_date', models.DateField(blank=True, null=True, verbose_name='首播日期')),
                ('collection_num', models.IntegerField(default=0, verbose_name='收藏数')),
                ('is_public', models.BooleanField(default=False, verbose_name='是否公开')),
                ('is_approved', models.BooleanField(default=False, verbose_name='是否通过审核')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('actor', models.ManyToManyField(blank=True, related_name='actor', to='staffs.Staff', verbose_name='演出')),
            ],
            options={
                'verbose_name': '番剧信息',
                'verbose_name_plural': '番剧信息',
                'db_table': 'tb_anime',
            },
        ),
        migrations.CreateModel(
            name='AnimeAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='标题')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alias', to='animes.anime', verbose_name='作品')),
            ],
            options={
                'verbose_name': '作品别名',
                'verbose_name_plural': '作品别名',
                'db_table': 'tb_anime_alias',
            },
        ),
    ]
