# Generated by Django 3.2.5 on 2021-12-02 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='标题')),
                ('title_cn', models.CharField(blank=True, max_length=100, verbose_name='中文标题')),
                ('description', models.TextField(blank=True, null=True, verbose_name='简介')),
                ('cover', models.ImageField(upload_to='animes/cover', verbose_name='封面图片')),
                ('cover_small', models.ImageField(upload_to='animes/cover_small', verbose_name='封面图片(小)')),
                ('collection_num', models.IntegerField(default=0, verbose_name='收藏数')),
                ('is_public', models.BooleanField(default=False, verbose_name='是否公开')),
                ('is_approved', models.BooleanField(default=False, verbose_name='是否通过审核')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '番剧信息',
                'verbose_name_plural': '番剧信息',
                'db_table': 'tb_anime',
            },
        ),
    ]
