# Generated by Django 3.2.5 on 2021-12-24 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staffs', '0001_initial'),
        ('animes', '0001_initial'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='contributor',
            field=models.ManyToManyField(related_name='anime_contributor', to=settings.AUTH_USER_MODEL, verbose_name='贡献者'),
        ),
        migrations.AddField(
            model_name='anime',
            name='create_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anime_create_user', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='anime',
            name='director',
            field=models.ManyToManyField(blank=True, related_name='director', to='staffs.Staff', verbose_name='导演'),
        ),
        migrations.AddField(
            model_name='anime',
            name='music',
            field=models.ManyToManyField(blank=True, related_name='music', to='staffs.Staff', verbose_name='音乐'),
        ),
        migrations.AddField(
            model_name='anime',
            name='original',
            field=models.ManyToManyField(blank=True, related_name='original', to='staffs.Staff', verbose_name='原作'),
        ),
        migrations.AddField(
            model_name='anime',
            name='producer',
            field=models.ManyToManyField(blank=True, related_name='producer', to='staffs.Staff', verbose_name='制作'),
        ),
        migrations.AddField(
            model_name='anime',
            name='script',
            field=models.ManyToManyField(blank=True, related_name='script', to='staffs.Staff', verbose_name='脚本'),
        ),
        migrations.AddField(
            model_name='anime',
            name='storyboard',
            field=models.ManyToManyField(blank=True, related_name='storyboard', to='staffs.Staff', verbose_name='分镜'),
        ),
        migrations.AddField(
            model_name='anime',
            name='tags',
            field=models.ManyToManyField(blank=True, to='tags.Tag', verbose_name='标签'),
        ),
    ]
