# Generated by Django 3.2.5 on 2021-11-29 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='score_0',
        ),
        migrations.AddField(
            model_name='anime',
            name='score_10',
            field=models.IntegerField(default=0, verbose_name='10分'),
        ),
        migrations.AddField(
            model_name='anime',
            name='score_6',
            field=models.IntegerField(default=0, verbose_name='6分'),
        ),
        migrations.AddField(
            model_name='anime',
            name='score_7',
            field=models.IntegerField(default=0, verbose_name='7分'),
        ),
        migrations.AddField(
            model_name='anime',
            name='score_8',
            field=models.IntegerField(default=0, verbose_name='8分'),
        ),
        migrations.AddField(
            model_name='anime',
            name='score_9',
            field=models.IntegerField(default=0, verbose_name='9分'),
        ),
    ]
