# Generated by Django 3.2.5 on 2021-12-11 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('staffs', '0001_initial'),
        ('animes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='actor',
            field=models.ManyToManyField(blank=True, related_name='actor', to='staffs.Staff', verbose_name='演出'),
        ),
        migrations.AddField(
            model_name='anime',
            name='air_date',
            field=models.DateField(blank=True, null=True, verbose_name='首播日期'),
        ),
        migrations.AddField(
            model_name='anime',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='制片国家'),
        ),
        migrations.AddField(
            model_name='anime',
            name='cover_medium',
            field=models.ImageField(default='', upload_to='animes/cover_medium', verbose_name='中等尺寸封面图片'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anime',
            name='director',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='director', to='staffs.staff', verbose_name='导演'),
        ),
        migrations.AddField(
            model_name='anime',
            name='epi_num',
            field=models.IntegerField(default=1, verbose_name='集数'),
        ),
        migrations.AddField(
            model_name='anime',
            name='music',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='music', to='staffs.staff', verbose_name='音乐'),
        ),
        migrations.AddField(
            model_name='anime',
            name='original',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original', to='staffs.staff', verbose_name='原作'),
        ),
        migrations.AddField(
            model_name='anime',
            name='producer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='producer', to='staffs.staff', verbose_name='制作'),
        ),
        migrations.AddField(
            model_name='anime',
            name='script',
            field=models.ManyToManyField(blank=True, related_name='script', to='staffs.Staff', verbose_name='脚本'),
        ),
        migrations.AddField(
            model_name='anime',
            name='storyboard',
            field=models.ManyToManyField(blank=True, related_name='storyboard', to='staffs.Staff', verbose_name='分镜'),
        ),
        migrations.AddField(
            model_name='anime',
            name='tags',
            field=models.ManyToManyField(blank=True, to='tags.Tag', verbose_name='标签'),
        ),
        migrations.AddField(
            model_name='anime',
            name='website',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='官网'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='cover_small',
            field=models.ImageField(upload_to='animes/cover_small', verbose_name='封面图片(正)'),
        ),
        migrations.CreateModel(
            name='AnimeAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='标题')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alias', to='animes.anime', verbose_name='作品')),
            ],
            options={
                'verbose_name': '作品别名',
                'verbose_name_plural': '作品别名',
                'db_table': 'tb_anime_alias',
            },
        ),
    ]
