# Generated by Django 3.2.5 on 2021-11-29 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('places', '0001_initial'),
        ('animes', '0002_auto_20211129_1420'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anime',
            options={'verbose_name': '番剧信息', 'verbose_name_plural': '番剧信息'},
        ),
        migrations.RemoveField(
            model_name='anime',
            name='collection_num',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='score_1',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='score_10',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='score_2',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='score_3',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='score_4',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='score_5',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='score_6',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='score_7',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='score_8',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='score_9',
        ),
        migrations.AddField(
            model_name='anime',
            name='contributor',
            field=models.ManyToManyField(related_name='anime_contributor', to=settings.AUTH_USER_MODEL, verbose_name='贡献者'),
        ),
        migrations.AddField(
            model_name='anime',
            name='create_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='anime_create_user', to='users.user', verbose_name='创建者'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anime',
            name='place',
            field=models.ManyToManyField(blank=True, related_name='anime_related', to='places.Place', verbose_name='相关地点'),
        ),
        migrations.AddField(
            model_name='anime',
            name='status',
            field=models.IntegerField(choices=[(0, '未发布'), (1, '待审核'), (2, '已发布'), (3, '审核失败')], default=0, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='简介'),
        ),
        migrations.AlterModelTable(
            name='anime',
            table='tb_anime',
        ),
    ]
