# Generated by Django 3.2.5 on 2021-12-12 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0001_initial'),
        ('animes', '0003_auto_20211211_2348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='director',
        ),
        migrations.AddField(
            model_name='anime',
            name='director',
            field=models.ManyToManyField(blank=True, related_name='director', to='staffs.Staff', verbose_name='导演'),
        ),
        migrations.RemoveField(
            model_name='anime',
            name='music',
        ),
        migrations.AddField(
            model_name='anime',
            name='music',
            field=models.ManyToManyField(blank=True, related_name='music', to='staffs.Staff', verbose_name='音乐'),
        ),
        migrations.RemoveField(
            model_name='anime',
            name='original',
        ),
        migrations.AddField(
            model_name='anime',
            name='original',
            field=models.ManyToManyField(blank=True, related_name='original', to='staffs.Staff', verbose_name='原作'),
        ),
        migrations.RemoveField(
            model_name='anime',
            name='producer',
        ),
        migrations.AddField(
            model_name='anime',
            name='producer',
            field=models.ManyToManyField(blank=True, related_name='producer', to='staffs.Staff', verbose_name='制作'),
        ),
    ]
