# Generated by Django 3.2.5 on 2021-11-30 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0003_auto_20211129_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='image',
        ),
        migrations.AddField(
            model_name='anime',
            name='cover',
            field=models.ImageField(default='', upload_to='animes/cover', verbose_name='封面图片'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anime',
            name='cover_small',
            field=models.ImageField(default='', upload_to='animes/cover_small', verbose_name='封面图片(小)'),
            preserve_default=False,
        ),
    ]
