# Generated by Django 3.2.5 on 2021-12-02 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0005_auto_20211202_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='cover',
            field=models.ImageField(upload_to='animes/cover', verbose_name='封面图片'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='cover_small',
            field=models.ImageField(upload_to='animes/cover_small', verbose_name='封面图片(小)'),
        ),
    ]
