# Generated by Django 3.2.5 on 2021-12-02 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0006_auto_20211202_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='status',
        ),
        migrations.AddField(
            model_name='anime',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='是否通过审核'),
        ),
        migrations.AddField(
            model_name='anime',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='是否公开'),
        ),
    ]
