# Generated by Django 3.2.5 on 2021-12-11 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='animes/staff/avatar', verbose_name='头像')),
                ('description', models.TextField(blank=True, null=True, verbose_name='简介')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'staff信息',
                'verbose_name_plural': 'staff信息',
                'db_table': 'tb_staff',
            },
        ),
    ]
